name: Hilla rentingCar workflow

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  build-app-using-java:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'jetbrains'
          architecture: x64

  run-npm-install:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
     - name: Install dependencies
       run: npm install
     - run: npm run dev
