name: CI for rentingCar 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'jetbrains'
          architecture: x64
          
      - name: Build and test backend
        working-directory: ./rentingCar
        run: mvn clean verify

  build-frontend:
    needs: build-backend
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install, lint, and build frontend
        working-directory: ./rentingCar
        run: |
            npm ci
            npm run build
