name: CI for rentingCar

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build and test backend (generate frontend files)
        working-directory: ./rentingCar
        run: mvn clean verify -Pproduction

      - name: Install frontend dependencies
        working-directory: ./rentingCar
        run: npm ci

      - name: Build frontend
        working-directory: ./rentingCar
        run: npm run build

  docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/rentingcar:latest ./rentingCar

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/rentingcar:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/rentingcar:latest

      - name: Tag image for ECR
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/rentingcar:latest ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push image to Amazon ECR
        run: docker push ${{ secrets.ECR_REPOSITORY }}:latest 